version: '3.8'

services:
  # Frontend service (React)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      # For development mode hot-reloading (comment out in production)
      - ./src:/app/src
      - ./public:/app/public
    environment:
      # Set to production or development as needed
      - NODE_ENV=production
      # If you have a separate API, set the URL here
      - REACT_APP_API_URL=http://mcs09-load-balancer-1014002416.ap-southeast-1.elb.amazonaws.com
    restart: unless-stopped
    # Use this for development mode instead
    # command: npm start